# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: Discord-installer.spec

# add or remove files that should be synced
files_to_sync:
    - Discord-installer.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: Discord-installer
# downstream (Fedora) RPM package name
downstream_package_name: Discord-installer

jobs:
- job: copr_build
  trigger: commit
  branch: release
  update_release: false
  targets: [fedora-all]
  owner: gui1ty
  project: discord
